FROM node:20

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port de l'API
EXPOSE 3050

# Démarrer le serveur en mode développement
CMD ["npm", "run", "start:dev"]
